version: "2"

services:
  was:
    build: was
    extends: 
      service: was
      file: common-services.yml
    volumes: 
    - $PWD/tmp:/usr/local/webapp/ROOT

  httpd:
    image: sangah/apache-pmis
    ports:
    - "80:80"
    environment: 
    - APACHE_SSL=0